# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deck Flatpak Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flatpak-x86_64:
    name: Build x86_64 Flatpak
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.10
      options: --privileged
      volumes:
        - /usr:/host/usr
        - /opt:/host/opt

    steps:
      - name: Recover host disk space
        run: |
          rm -rf /host/opt/hostedtoolcache/CodeQL
          rm -rf /host/opt/hostedtoolcache/go
          rm -rf /host/usr/local/lib/android
          rm -rf /host/usr/local/.ghcup
          rm -rf /host/usr/local/share/powershell
          rm -rf /host/usr/share/swift
          rm -rf /host/usr/share/dotnet

      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Store Git version
        shell: bash
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          GIT_DESC="$(git describe --always --first-parent --dirty=-modified)"
          if [ -z "${GIT_DESC}" ]; then
            GIT_DESC="unknown"
          fi
          echo "GIT_DESC=${GIT_DESC}" >> "${GITHUB_ENV}"

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: packaging/flatpak/org.mixxx.Mixxx.yaml
          arch: x86_64
          build-bundle: false
          upload-artifact: false

      - name: Create Flatpak bundle
        shell: bash
        run: |
          flatpak build-bundle repo \
            --arch=x86_64 \
            --runtime-repo=https://dl.flathub.org/repo/flathub.flatpakrepo \
            "Mixxx-${GIT_DESC}-x86_64.flatpak" \
            org.mixxx.Mixxx
          cp "Mixxx-${GIT_DESC}-x86_64.flatpak" Mixxx.flatpak

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Mixxx-flatpak-x86_64
          path: Mixxx.flatpak
          compression-level: 0
          retention-days: 3
